[package]
name = "vaultify"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
simplelog = "0.12.0"
log = "0.4.17"
diesel = { version = "2.1.0", features = ["sqlite"] }

[dependencies.rocket_sync_db_pools]
version = "=0.1.0-rc.3"
features = ["diesel_sqlite_pool"]